# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 01:45
from __future__ import unicode_literals

import block.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('block', '0018_image_user'),
        ('compose', '0017_auto_20160205_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date_moderated', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Map',
            },
        ),
        migrations.CreateModel(
            name='MapBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('page_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.PageSection')),
            ],
            options={
                'verbose_name': 'Block',
                'abstract': False,
                'verbose_name_plural': 'Blocks',
            },
        ),
        migrations.AddField(
            model_name='map',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='compose.MapBlock'),
        ),
        migrations.AddField(
            model_name='map',
            name='edit_state',
            field=models.ForeignKey(default=block.models._default_edit_state, on_delete=django.db.models.deletion.CASCADE, to='block.EditState'),
        ),
        migrations.AddField(
            model_name='map',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map', to='block.Link'),
        ),
        migrations.AddField(
            model_name='map',
            name='moderate_state',
            field=models.ForeignKey(default=block.models._default_moderate_state, on_delete=django.db.models.deletion.CASCADE, to='block.ModerateState'),
        ),
        migrations.AddField(
            model_name='map',
            name='user_moderated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='map',
            unique_together=set([('block', 'moderate_state')]),
        ),
    ]
