# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('compose', '0018_auto_20170320_1110'), ('compose', '0019_auto_20170321_1027'), ('compose', '0020_auto_20170321_2011'), ('compose', '0021_auto_20170321_2121')]

    dependencies = [
        ('compose', '0017_auto_20160205_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_width',
            field=models.CharField(choices=[('col-12 col-md-6', 'Half when Big'), ('col-12', 'Full Width'), ('col-12 col-sm-4 col-md-3', 'Third or Less'), ('col-12 col-sm-6 col-md-4 col-lg-3', 'Half or Less'), ('col-12 col-sm-6 col-md-4', 'Text Bottom')], default='col-12 col-md-6', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('pull-right', 'Text Left'), ('pull-left', 'Text Right'), ('w-100', 'Text Top'), ('w-100', 'Text Bottom'), ('hidden', 'Text Only'), ('visible', 'Picture Only')], default='pull-right', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_size',
            field=models.CharField(choices=[('col-6', 'Half Width'), ('col-4', 'Third Width'), ('col-3', 'Quarter Width')], default='col-6', max_length=32),
        ),
        migrations.AddField(
            model_name='article',
            name='heading_level',
            field=models.CharField(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4')], default='h2', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('pull-left', 'Text Left'), ('pull-right', 'Text Right'), ('w-100', 'Text Top'), ('w-100', 'Text Bottom'), ('hidden', 'Text Only'), ('visible', 'Picture Only')], default='pull-left', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_size',
            field=models.CharField(choices=[('w-100', 'Full Width'), ('w-75', '3 Quarters Width'), ('w-50', 'Half Width'), ('w-25', 'Quarter Width')], default='w-50', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('pull-right ml-3 mb-3 mt-3', 'Text Left'), ('pull-left mr-3 mb-3 mt-3', 'Text Right'), ('w-100 mb-2 mt-3', 'Text Top'), ('w-100 mb-3 mt-2', 'Text Bottom'), ('hidden', 'Text Only'), ('visible', 'Picture Only')], default='pull-right ml-3 mb-3 mt-3', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_size',
            field=models.CharField(choices=[('w-100', 'Full Width'), ('w-75', '3 Quarters Width'), ('w-75', '2 Thirds Width'), ('w-50', 'Half Width'), ('w-25', 'Third Width'), ('w-25', 'Quarter Width')], default='w-50', max_length=64),
        ),
        migrations.AddField(
            model_name='feature',
            name='heading_level',
            field=models.CharField(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4')], default='h4', max_length=2),
        ),
    ]
