# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('compose', '0018_auto_20170322_0045'), ('compose', '0019_auto_20170322_0053'), ('compose', '0020_auto_20170322_0057')]

    dependencies = [
        ('compose', '0017_auto_20160205_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('pull-right ml-3 mb-3 mt-3', 'Text Left'), ('pull-left mr-3 mb-3 mt-3', 'Text Right'), ('w-100 mb-2 mt-3', 'Text Top'), ('w-100 mb-3 mt-2', 'Text Bottom'), ('hidden', 'Text Only'), ('visible', 'Picture Only')], default='pull-right ml-3 mb-3 mt-3', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_size',
            field=models.CharField(choices=[('w-100', 'Full Width'), ('w-75', '3 Quarters Width'), ('w-75', '2 Thirds Width'), ('w-50', 'Half Width'), ('w-25', 'Third Width'), ('w-25', 'Quarter Width')], default='w-50', max_length=64),
        ),
        migrations.AddField(
            model_name='article',
            name='css_width',
            field=models.CharField(choices=[('col-12 col-md-6', 'Half or Bigger'), ('col-12', 'Full Width'), ('col-12 col-sm-4 col-md-3', 'Third or Smaller'), ('col-12 col-sm-6 col-md-4 col-lg-3', 'Half or Smaller'), ('col-12 col-sm-6 col-md-4', 'Third or Bigger')], default='col-12 col-md-6', max_length=12),
        ),
        migrations.AddField(
            model_name='article',
            name='heading_level',
            field=models.CharField(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4')], default='h2', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('text_left', 'Text Left'), ('text_right', 'Text Right'), ('text_top', 'Text Top'), ('text_bottom', 'Text Bottom'), ('text_only', 'Text Only'), ('picture_only', 'Picture Only')], default='pull-right ml-3 mb-3 mt-3', max_length=12),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_size',
            field=models.CharField(choices=[('1-2', 'Half Width'), ('1-3', 'Third Width'), ('1-4', 'Quarter Width')], default='w-50', max_length=3),
        ),
        migrations.AddField(
            model_name='feature',
            name='css_width',
            field=models.CharField(choices=[('col-12 col-md-6', 'Half or Bigger'), ('col-12', 'Full Width'), ('col-12 col-sm-4 col-md-3', 'Third or Smaller'), ('col-12 col-sm-6 col-md-4 col-lg-3', 'Half or Smaller'), ('col-12 col-sm-6 col-md-4', 'Third or Bigger')], default='col-12 col-md-6', max_length=12),
        ),
        migrations.AddField(
            model_name='feature',
            name='heading_level',
            field=models.CharField(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4')], default='h2', max_length=2),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='css_width',
            field=models.CharField(choices=[('col-12 col-md-6', 'Half or Bigger'), ('col-12', 'Full Width'), ('col-12 col-sm-4 col-md-3', 'Third or Smaller'), ('col-12 col-sm-6 col-md-4 col-lg-3', 'Half or Smaller'), ('col-12 col-sm-6 col-md-4', 'Third or Bigger')], default='col-12 col-md-6', max_length=12),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='heading_level',
            field=models.CharField(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4')], default='h2', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('text_left', 'Text Left'), ('text_right', 'Text Right'), ('text_top', 'Text Top'), ('text_bottom', 'Text Bottom'), ('text_only', 'Text Only'), ('picture_only', 'Picture Only')], default='pull-right ml-3 mb-3 mt-3', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_size',
            field=models.CharField(choices=[('1-2', 'Half Width'), ('1-3', 'Third Width'), ('1-4', 'Quarter Width')], default='w-50', max_length=64),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
