# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0017_auto_20160205_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_width',
            field=models.CharField(choices=[('col-12 col-md-6', 'Half when Big'), ('col-12', 'Full Width'), ('col-12 col-sm-6 col-md-4 col-lg-3 pure-xl-2', 'Half or Less'), ('col-12 col-sm-6 col-md-4', 'Text Bottom')], default='col-12 col-md-6', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('pull-right', 'Text Left'), ('pull-left', 'Text Right'), ('w-100', 'Text Top'), ('w-100', 'Text Bottom'), ('hidden', 'Text Only'), ('visible', 'Picture Only')], default='pull-right', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_size',
            field=models.CharField(choices=[('col-6', 'Half Width'), ('col-4', 'Third Width'), ('col-3', 'Quarter Width')], default='col-6', max_length=32),
        ),
    ]
