# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0018_auto_20170320_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='heading_level',
            field=models.CharField(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4')], default='h2', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('pull-left', 'Text Left'), ('pull-right', 'Text Right'), ('w-100', 'Text Top'), ('w-100', 'Text Bottom'), ('hidden', 'Text Only'), ('visible', 'Picture Only')], default='pull-left', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_size',
            field=models.CharField(choices=[('w-100', 'Full Width'), ('w-75', '3 Quarters Width'), ('w-50', 'Half Width'), ('w-25', 'Quarter Width')], default='w-50', max_length=32),
        ),
    ]
