# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0019_auto_20170321_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('pull-right ml-3 mb-3 mt-3', 'Text Left'), ('pull-left mr-3 mb-3 mt-3', 'Text Right'), ('w-100 mb-2 mt-3', 'Text Top'), ('w-100 mb-3 mt-2', 'Text Bottom'), ('hidden', 'Text Only'), ('visible', 'Picture Only')], default='pull-right ml-3 mb-3 mt-3', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_width',
            field=models.CharField(choices=[('col-12 col-md-6', 'Half when Big'), ('col-12', 'Full Width'), ('col-12 col-sm-6 col-md-4 col-lg-2', 'Half or Less'), ('col-12 col-sm-6 col-md-4', 'Text Bottom')], default='col-12 col-md-6', max_length=64),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_size',
            field=models.CharField(choices=[('w-100', 'Full Width'), ('w-75', '3 Quarters Width'), ('w-75', '2 Thirds Width'), ('w-50', 'Half Width'), ('w-25', 'Third Width'), ('w-25', 'Quarter Width')], default='w-50', max_length=64),
        ),
    ]
