# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compose', '0020_auto_20170321_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='heading_level',
            field=models.CharField(choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4')], default='h4', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_width',
            field=models.CharField(choices=[('col-12 col-md-6', 'Half when Big'), ('col-12', 'Full Width'), ('col-12 col-sm-4 col-md-3', 'Third or Less'), ('col-12 col-sm-6 col-md-4 col-lg-3', 'Half or Less'), ('col-12 col-sm-6 col-md-4', 'Text Bottom')], default='col-12 col-md-6', max_length=64),
        ),
    ]
